name: Playwright Tests

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install backend dependencies
        run: |
          cd backend
          bundle install
          gem install rackup

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      - name: Start backend server
        run: |
          cd backend
          ruby app.rb &
        env:
          RACK_ENV: test

      - name: Wait for backend to be ready
        run: sleep 5

      - name: Seed Database
        run: |
          curl -X POST http://localhost:4567/api/seed

      - name: Start frontend
        run: |
          cd frontend
          yarn start &

      - name: Wait for Frontend to be Ready
        run: sleep 10

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
